### PR TITLE
display entire voting option

### PR DESCRIPTION
**Pull request by Zen-44**

### CODE REVIEW

**Comment by midenaio** [comment]
Hey @Zen-44, it was not merged to master. Would you like to reopen it?

**Comment by Zen-44** [comment]
> Hey @Zen-44, it was not merged to master. Would you like to reopen it?

I believe the change was not working as expected since voting options still don't display completely on the vercel preview.
image

**Comment by midenaio** [comment]
We use Chakra components: https://v2.chakra-ui.com/docs/components/text#truncate-text
I guess something like `noOfLines={2}` should fix it

**Comment by midenaio** [comment]
It doesn't seem to work
image

**Comment by Zen-44** [comment]
A new pull request has been opened

**Pull request closed without merging**
